### PR TITLE
flixel 5 fix (again)

### PR DESCRIPTION
**Pull request by mayo78**
not sure how this fix got undone in this specific part but now it compiles for flixel 4.11 and flixel 5 users alike

### CODE REVIEW

**Comment by mayo78** [comment]
@BemboLikePizza hey!

**Comment by mayo78** [comment]
@BemboLikePizza

**Comment by BemboLikePizza** [comment]
?

**Comment by mayo78** [comment]
it makes it so you can compile the game on flixel 5

**Comment by mayo78** [comment]
MERGE THIS FhjkDSGHJKLSDFHLDFJKGHLJKDFHGKLDFJHBJKLDFN KLJNFDLKVKDFJN VLKDFJNc

**Comment by BemboLikePizza** [comment]
how i can do that?

**Pull request merged**
