### PR TITLE
updated source code

### PR DESCRIPTION
**Pull request by mayo78**
this fork is like 30 commits behind

### CODE REVIEW

**Comment by mayo78** [comment]
@BemboLikePizza erm... pull?

**Comment by mayo78** [comment]
@BemboLikePizza  pull this please!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mayo78** [comment]
i forgot to explain why i wanted you to pull this so bad but for some reason every single vsdave fork defaulted to be a fork of your fork because the original repo was privated for 3.5

**Comment by BemboLikePizza** [comment]
what

**Comment by mayo78** [comment]
this repository of code, which was a fork of the dave and bambi repository, was made into a normal repository instead of a fork because the original dave and bambi repository from moldygh was privatized for the next dave and bambi update, and every previous fork of the original dave and bambi was made into a fork of this repository

**Comment by BemboLikePizza** [comment]
Interesting.

**Comment by BemboLikePizza** [comment]
wym about pull

**Pull request merged**
